
language: python

python:
  - "3.6"

install:
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls 
  - pip install -r requirements.txt
# command to run tests
script:
  - python -m unittest discover test
  - coverage run --source sslplay test/test.py
  - coverage report -m
branches:
  only:
  - master
after_success:
  - coveralls